apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-1
spec:
  ingressClassName: nginx
  rules:
  - host: javawebapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: javawebapp-service
            port:
              number: 80
  - host: mavenwebapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mavenwebapp-service
            port:
              number: 80
