apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 2
  selector:
    name: springapp
  template:
    metadata:
      name: springapp-pod
      labels:
        name: springapp
    spec:
      containers:
      - image: dockerp2pro/spring-boot-mongo:1
        name: springbootcontainer
        ports:
        - containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
        #labels:
        #name: springbootservice
  name: springbootservice
spec:
  type: NodePort
  selector:
    name: springapp
  ports:
  - port: 80
    targetPort: 8080
