apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - image: dockerp2pro/java-web-app-demo
        name: javawebappcontainer
        ports:
        - containerPort: 8080
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 1Gi
        #  limits:
        #    cpu: 200m
        #    memory: 4Gi
---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  type: LoadBalancer		#ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javawebapp
