apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - image: dockerp2pro/maven-web-application
        name: mavenwebappcontainer
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 200m
            memory: 4Gi
---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapp-service
spec:
  type: LoadBalancer		#ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mavenwebapp
