apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dockerp2pro/spring-boot-mongo:latest
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
#  ports:
#    - port: 80
#      name: http
#      targetPort: 8080
#    - port: 433
#      name: https
#      targetPort: 8080
  selector:
    name: springboot
